name: Build Boards

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build ESP32 DevKit V1
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Firmware
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          # Forzamos el target a esp32 clásico
          idf.py set-target esp32
          idf.py build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi-devkit-v1
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/ota_data_initial.bin
            build/*.bin
