name: Build Boards

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Compilar Firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4    # Cambiado a v5.4 para cumplir el requisito
          target: esp32
